(list
  (typeof 4)
  (typeof '())
  (typeof (proc () 'nil))
  (typeof (macro (proc () 'nil)))
  (typeof (current-environment))
  (typeof +)
  (typeof 'foo)
  (typeof "foo")
  (typeof nil)
  (typeof \a)
  )
